#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPS_DIR="$PROJECT_DIR/.deps"
SOURCE_DIR="$DEPS_DIR/iceberg-cpp-src"
BUILD_DIR="$DEPS_DIR/iceberg-cpp-build"
PREFIX="$DEPS_DIR/iceberg-cpp"
BUILD_ENV="$DEPS_DIR/build-env.sh"
ICEBERG_ENV="$DEPS_DIR/iceberg-env.sh"
MARKER_NAME=".root4duckdb-shared-install"

ICEBERG_TAG="v0.3.0"
ICEBERG_COMMIT="0284683f7e1dd5742913d5f0a7c4b48e445df7a4"

JOBS=4
CLEAN=0

usage() {
    cat <<'USAGE'
Usage: ./build-iceberg.sh [options]

Builds and installs Apache Iceberg C++ once as shared libraries and static
archives. It does not build DuckDB or ROOT4DuckDB.

Options:
  -j, --jobs N       Parallel build jobs (default: 4)
  --clean            Rebuild Iceberg from a clean build/install tree
  -h, --help         Show this help

To select a compiler explicitly, set CC and CXX before this command. The same
compiler is then reused automatically by build-root4duckdb.sh.
USAGE
}

while (($#)); do
    case "$1" in
        -j|--jobs)
            [[ $# -ge 2 ]] || {
                echo "[ERROR] Missing jobs value" >&2
                exit 2
            }
            JOBS="$2"
            shift 2
            ;;
        --clean)
            CLEAN=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[ERROR] Unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

[[ "$JOBS" =~ ^[1-9][0-9]*$ ]] || {
    echo "[ERROR] --jobs must be a positive integer" >&2
    exit 2
}

if ((JOBS > 8)); then
    echo "[WARN] --jobs=$JOBS can exceed lxplus memory limits; 4 is the safe default."
fi

mkdir -p "$DEPS_DIR"
PREFIX="$(mkdir -p "$PREFIX" && cd "$PREFIX" && pwd -P)"

if ((CLEAN)); then
    for target in "$BUILD_DIR" "$PREFIX"; do
        case "$target" in
            "$DEPS_DIR"/*) ;;
            *)
                echo "[ERROR] Refusing to clean path outside $DEPS_DIR: $target" >&2
                exit 2
                ;;
        esac

        cmake -E remove_directory "$target"
    done

    mkdir -p "$PREFIX"
fi

"$PROJECT_DIR/scripts/detect-build-environment.sh" --write "$BUILD_ENV"

# shellcheck disable=SC1090
source "$BUILD_ENV"
hash -r

for tool in cmake python3; do
    command -v "$tool" >/dev/null 2>&1 || {
        echo "[ERROR] Required tool not found: $tool" >&2
        exit 1
    }
done

cmake_version="$(
    cmake --version |
        sed -nE '1s/.* ([0-9]+)\.([0-9]+).*/\1 \2/p'
)"
read -r cmake_major cmake_minor <<<"${cmake_version:-0 0}"

if ((cmake_major < 3 ||
     (cmake_major == 3 && cmake_minor < 28))); then
    echo "[ERROR] Apache Iceberg SQL catalog requires CMake 3.28+" >&2
    exit 1
fi

smoke="$DEPS_DIR/cxx23-smoke"
"$CXX" -std=c++23 -x c++ -o "$smoke" - <<'CPP'
#include <expected>
#include <ranges>
#include <string>

int main() {
    std::expected<int, std::string> value = 1;
    auto text =
        std::views::iota(0, 1) |
        std::ranges::to<std::string>();

    return value.value() == 1 && text.size() == 1 ? 0 : 1;
}
CPP

"$smoke"
echo "[OK] C++23 compiler: $CXX ($("$CXX" --version | head -1))"

write_environment() {
    local lib_path="$PREFIX/lib:$PREFIX/lib64"

    cat > "$ICEBERG_ENV" <<ENV
# Generated by build-iceberg.sh. Source this only when invoking tools manually.
source '$BUILD_ENV'
export ROOT4DUCKDB_ICEBERG_PREFIX='$PREFIX'
export LD_LIBRARY_PATH='$lib_path':\${LD_LIBRARY_PATH:-}
ENV

    chmod 0644 "$ICEBERG_ENV"
}

if [[ -f "$PREFIX/$MARKER_NAME" ]]; then
    write_environment

    if "$PROJECT_DIR/scripts/check-iceberg.sh" \
        --prefix "$PREFIX" --quiet; then
        echo "[OK] Apache Iceberg C++ is already installed: $PREFIX"
        echo "     Use --clean to rebuild it."
        exit 0
    fi

    echo "[WARN] Existing Iceberg install is incomplete; rebuilding it." >&2
fi

[[ -x "${GIT_BIN:-}" ]] || {
    echo "[ERROR] GIT_BIN is unavailable" >&2
    exit 1
}

if [[ -e "$SOURCE_DIR" && ! -d "$SOURCE_DIR/.git" ]]; then
    echo "[WARN] Removing incomplete Iceberg source tree: $SOURCE_DIR" >&2
    cmake -E remove_directory "$SOURCE_DIR"
fi

if [[ ! -d "$SOURCE_DIR/.git" ]]; then
    "$GIT_BIN" clone \
        --filter=blob:none \
        --no-checkout \
        https://github.com/apache/iceberg-cpp.git \
        "$SOURCE_DIR"
fi

"$GIT_BIN" -C "$SOURCE_DIR" fetch \
    --force \
    --depth 1 \
    origin \
    "$ICEBERG_COMMIT"

"$GIT_BIN" -C "$SOURCE_DIR" checkout \
    --force \
    --detach \
    "$ICEBERG_COMMIT"

actual_commit="$("$GIT_BIN" -C "$SOURCE_DIR" rev-parse HEAD)"
[[ "$actual_commit" == "$ICEBERG_COMMIT" ]] || {
    echo "[ERROR] Iceberg commit mismatch: $actual_commit" >&2
    exit 1
}

# Keep diagnostics without inheriting dependency warnings-as-errors.
python3 - "$SOURCE_DIR/CMakeLists.txt" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text()

enabled = "set(CMAKE_COMPILE_WARNING_AS_ERROR ON)"
disabled = "set(CMAKE_COMPILE_WARNING_AS_ERROR OFF)"

if enabled in text:
    path.write_text(text.replace(enabled, disabled, 1))
elif disabled not in text:
    raise SystemExit("[ERROR] Unexpected Iceberg CMake warning policy")
PY

# Keep a failed build resumable. --clean is the explicit reset path.
mkdir -p "$BUILD_DIR" "$PREFIX"

generator=()
if command -v ninja >/dev/null 2>&1; then
    generator=(-G Ninja)
elif command -v ninja-build >/dev/null 2>&1; then
    shim="$DEPS_DIR/build-tools"
    mkdir -p "$shim"
    ln -sf "$(command -v ninja-build)" "$shim/ninja"
    export PATH="$shim:$PATH"
    generator=(-G Ninja)
fi

shared_linker_flags=""
if [[ "$(uname -s)" == "Linux" ]]; then
    # Keep vendored implementation symbols behind the Iceberg DSO boundary.
    shared_linker_flags="-Wl,--exclude-libs,ALL"
fi

cmake \
    -S "$SOURCE_DIR" \
    -B "$BUILD_DIR" \
    "${generator[@]}" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$PREFIX" \
    -DCMAKE_C_COMPILER="$CC" \
    -DCMAKE_CXX_COMPILER="$CXX" \
    -DCMAKE_CXX_STANDARD=23 \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DCMAKE_INSTALL_RPATH='$ORIGIN' \
    -DCMAKE_SHARED_LINKER_FLAGS="$shared_linker_flags" \
    -DICEBERG_BUILD_TESTS=OFF \
    -DICEBERG_BUILD_EXAMPLES=OFF \
    -DICEBERG_BUILD_REST=OFF \
    -DICEBERG_BUILD_SQL_CATALOG=ON \
    -DICEBERG_SQL_SQLITE=ON \
    -DICEBERG_SQL_POSTGRESQL=OFF \
    -DICEBERG_SQL_MYSQL=OFF \
    -DICEBERG_BUILD_SHARED=ON \
    -DICEBERG_BUILD_STATIC=ON \
    -DICEBERG_BUILD_BUNDLE=ON

cmake --build "$BUILD_DIR" --parallel "$JOBS"
cmake --install "$BUILD_DIR"

cxx_version="$("$CXX" --version | sed -n '1p')"

cat > "$PREFIX/$MARKER_NAME" <<MARKER
ROOT4DUCKDB_ICEBERG_LINKAGE=shared+static
ICEBERG_TAG=$ICEBERG_TAG
ICEBERG_COMMIT=$ICEBERG_COMMIT
CXX=$CXX
CXX_VERSION=$cxx_version
MARKER

write_environment
"$PROJECT_DIR/scripts/check-iceberg.sh" --prefix "$PREFIX"

echo "[OK] Apache Iceberg C++ $ICEBERG_TAG installed: $PREFIX"
echo "[OK] Shared libraries support the bundled CLI."
echo "[OK] Static archives support the portable extension."
