# Parquet stores the external ROOT physical-index tables.
duckdb_extension_load(parquet)

# ROOT4DuckDB itself.
file(READ "${CMAKE_CURRENT_LIST_DIR}/VERSION" ROOT4DUCKDB_VERSION)
string(STRIP "${ROOT4DUCKDB_VERSION}" ROOT4DUCKDB_VERSION)

set(ROOT4DUCKDB_LINK_OPTIONS "")
if(ROOT4DUCKDB_LOADABLE_ONLY)
    list(APPEND ROOT4DUCKDB_LINK_OPTIONS DONT_LINK)
endif()

duckdb_extension_load(root
    SOURCE_DIR ${CMAKE_CURRENT_LIST_DIR}
    EXTENSION_VERSION "v${ROOT4DUCKDB_VERSION}"
    LOAD_TESTS
    ${ROOT4DUCKDB_LINK_OPTIONS}
)
